# Generated by Django 4.2.3 on 2023-07-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=200)),
                ('numero_paginas', models.CharField(max_length=200)),
                ('ano_publicacao', models.CharField(max_length=200)),
                ('preco', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='livros')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero')),
            ],
        ),
    ]
